"""add language to posts

Revision ID: 570016705229
Revises: 88a42f79e1f9
Create Date: 2018-12-09 22:07:34.566623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570016705229'
down_revision = '88a42f79e1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
